// ═══════════════════════════════════════════════════
// SmartMeni — Registar predložaka
// ═══════════════════════════════════════════════════

export const TEMPLATES = [
  // ── Zelene nijanse ──
  {
    id: 'modern_minimal',
    name: 'Modern Minimal',
    desc: 'Čist, savremeni zeleni',
    brand: '#0d7a52',
    pageBg: '#f5f9f7',
    catColor: '#0d7a52',
    catBg: '#e0f5ec',
    catBorder: '#0d7a52',
    itemAccentBg: '#e0f5ec',
    priceColor: '#0d7a52',
    cardBg: '#ffffff',
  },
  {
    id: 'garden_fresh',
    name: 'Garden Fresh',
    desc: 'Svjetlo zelena, organsko',
    brand: '#2e7d32',
    pageBg: '#f4fbf4',
    catColor: '#2e7d32',
    catBg: '#dff0df',
    catBorder: '#2e7d32',
    itemAccentBg: '#dff0df',
    priceColor: '#2e7d32',
    cardBg: '#ffffff',
  },
  {
    id: 'sage',
    name: 'Sage',
    desc: 'Nježno zelenkasto',
    brand: '#5a7a5a',
    pageBg: '#f4f7f4',
    catColor: '#5a7a5a',
    catBg: '#e4ede4',
    catBorder: '#5a7a5a',
    itemAccentBg: '#e4ede4',
    priceColor: '#3d5c3d',
    cardBg: '#ffffff',
  },

  // ── Plave nijanse ──
  {
    id: 'mediterranean',
    name: 'Mediterranean',
    desc: 'Jadransko plavo',
    brand: '#1565a0',
    pageBg: '#f5f8ff',
    catColor: '#1565a0',
    catBg: '#ddeeff',
    catBorder: '#1565a0',
    itemAccentBg: '#ddeeff',
    priceColor: '#1565a0',
    cardBg: '#ffffff',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    desc: 'Duboko plava, svježe',
    brand: '#006994',
    pageBg: '#f3f8fb',
    catColor: '#006994',
    catBg: '#d6edf7',
    catBorder: '#006994',
    itemAccentBg: '#d6edf7',
    priceColor: '#006994',
    cardBg: '#ffffff',
  },
  {
    id: 'sky',
    name: 'Sky',
    desc: 'Nebeski, lagano',
    brand: '#0288d1',
    pageBg: '#f4faff',
    catColor: '#0288d1',
    catBg: '#ddf0fc',
    catBorder: '#0288d1',
    itemAccentBg: '#ddf0fc',
    priceColor: '#0277bd',
    cardBg: '#ffffff',
  },

  // ── Tople nijanse ──
  {
    id: 'cafe',
    name: 'Café',
    desc: 'Toplo smeđe',
    brand: '#5c3d2e',
    pageBg: '#fdf8f3',
    catColor: '#5c3d2e',
    catBg: '#faeeda',
    catBorder: '#5c3d2e',
    itemAccentBg: '#faeeda',
    priceColor: '#5c3d2e',
    cardBg: '#ffffff',
  },
  {
    id: 'pizzeria',
    name: 'Pizzeria',
    desc: 'Italijanski šarm',
    brand: '#b5451b',
    pageBg: '#fdf8f5',
    catColor: '#b5451b',
    catBg: '#faeada',
    catBorder: '#b5451b',
    itemAccentBg: '#faeada',
    priceColor: '#b5451b',
    cardBg: '#ffffff',
  },
  {
    id: 'fast_food',
    name: 'Fast Food',
    desc: 'Crvena, energično',
    brand: '#c0392b',
    pageBg: '#fff8f7',
    catColor: '#c0392b',
    catBg: '#fce8e6',
    catBorder: '#c0392b',
    itemAccentBg: '#fce8e6',
    priceColor: '#c0392b',
    cardBg: '#ffffff',
  },
  {
    id: 'amber',
    name: 'Amber',
    desc: 'Zlatno žuta, street food',
    brand: '#e65100',
    pageBg: '#fffbf5',
    catColor: '#e65100',
    catBg: '#fdebd0',
    catBorder: '#e65100',
    itemAccentBg: '#fdebd0',
    priceColor: '#bf360c',
    cardBg: '#ffffff',
  },

  // ── Tamne / elegantne nijanse ──
  {
    id: 'fine_dining',
    name: 'Fine Dining',
    desc: 'Tamno, elegantno',
    brand: '#1a1a2e',
    pageBg: '#f8f6f2',
    catColor: '#1a1a2e',
    catBg: '#e8e4dc',
    catBorder: '#1a1a2e',
    itemAccentBg: '#e8e4dc',
    priceColor: '#8b6914',
    cardBg: '#ffffff',
  },
  {
    id: 'pub',
    name: 'Pub & Bar',
    desc: 'Tamno drvo, muževno',
    brand: '#2c1810',
    pageBg: '#f5f0eb',
    catColor: '#2c1810',
    catBg: '#e8ddd0',
    catBorder: '#2c1810',
    itemAccentBg: '#e8ddd0',
    priceColor: '#8b4513',
    cardBg: '#ffffff',
  },

  // ── Posebne nijanse ──
  {
    id: 'lavender',
    name: 'Lavender',
    desc: 'Ljubičasto, spa & wellness',
    brand: '#6a1b9a',
    pageBg: '#faf5ff',
    catColor: '#6a1b9a',
    catBg: '#ede7f6',
    catBorder: '#6a1b9a',
    itemAccentBg: '#ede7f6',
    priceColor: '#4a148c',
    cardBg: '#ffffff',
  },
  {
    id: 'rose',
    name: 'Rose',
    desc: 'Roze, slastičarnica',
    brand: '#ad1457',
    pageBg: '#fff8fa',
    catColor: '#ad1457',
    catBg: '#fce4ec',
    catBorder: '#ad1457',
    itemAccentBg: '#fce4ec',
    priceColor: '#880e4f',
    cardBg: '#ffffff',
  },
  {
    id: 'slate',
    name: 'Slate',
    desc: 'Sivo, moderno',
    brand: '#37474f',
    pageBg: '#f7f8f9',
    catColor: '#37474f',
    catBg: '#e0e6ea',
    catBorder: '#37474f',
    itemAccentBg: '#e0e6ea',
    priceColor: '#263238',
    cardBg: '#ffffff',
  },
]

// Helper — vrati template po ID-u, default je modern_minimal
export const getTemplate = (id) =>
  TEMPLATES.find(t => t.id === id) || TEMPLATES[0]
