-- Biblioteka: HRANA + ostala PIĆA (faza 2)
-- Grupe: bezalkoholna (soft), topli napici (hot), pivo/vino/žestoko kao stavke
-- (beverage, bez recepta), topla jela (food), salate/predjela (salad),
-- doručak (breakfast), deserti (dessert).
-- Kalorije/alergeni se IZVODE iz sastojaka (kao 20260606000010). Beverage stavke
-- nemaju sastojke pa im se kalorije/alergeni postavljaju inline.

-- ─── RECEPTI ──────────────────────────────────────────────────────────────────
INSERT INTO public.recipe_library (id, name, name_en, category, emoji, suggested_price, prep_time, sort_order) VALUES
  -- Bezalkoholna
  ('domaca_limunada',   'Domaća limunada',     'Homemade Lemonade',   'soft', '🍋', 2.50, '3 min', 10),
  ('limunada_menta',    'Limunada sa mentom',  'Mint Lemonade',       'soft', '🍃', 2.80, '3 min', 20),
  ('ledeni_caj_breskva','Ledeni čaj breskva',  'Peach Iced Tea',      'soft', '🧊', 2.50, '3 min', 30),
  ('ledeni_caj_limun',  'Ledeni čaj limun',    'Lemon Iced Tea',      'soft', '🧊', 2.50, '3 min', 40),
  ('cijedjena_pomorandza','Cijeđena pomorandža','Fresh Orange Juice', 'soft', '🍊', 3.00, '2 min', 50),
  ('frape_vanila',      'Frape vanila',        'Vanilla Frappe',      'soft', '🥤', 3.20, '3 min', 60),
  ('frape_cokolada',    'Frape čokolada',      'Chocolate Frappe',    'soft', '🥤', 3.40, '3 min', 70),
  ('milkshake_jagoda',  'Milkshake jagoda',    'Strawberry Milkshake','soft', '🍓', 3.50, '3 min', 80),
  ('smoothie_sumsko',   'Smoothie šumsko voće','Berry Smoothie',      'soft', '🫐', 3.80, '3 min', 90),
  -- Topli napici
  ('topla_cokolada',    'Topla čokolada',      'Hot Chocolate',       'hot',  '🍫', 2.80, '3 min', 110),
  ('caj_nana',          'Čaj od nane',         'Mint Tea',            'hot',  '🍵', 1.80, '3 min', 120),
  ('crni_caj',          'Crni čaj',            'Black Tea',           'hot',  '🍵', 1.80, '3 min', 130),
  ('kakao',             'Kakao',               'Cocoa',               'hot',  '☕', 2.50, '3 min', 140),
  -- Topla jela
  ('cevapi',            'Ćevapi (10 kom)',     'Ćevapi',              'food', '🍢', 6.00, '15 min', 210),
  ('pljeskavica',       'Pljeskavica',         'Pljeskavica',         'food', '🍔', 5.50, '15 min', 220),
  ('raznjici',          'Ražnjići',            'Pork Skewers',        'food', '🍢', 6.00, '15 min', 230),
  ('mjesano_meso',      'Mješano meso',        'Mixed Grill',         'food', '🍖', 9.00, '18 min', 240),
  ('burek_meso',        'Burek sa mesom',      'Meat Burek',          'food', '🥟', 3.00, '10 min', 250),
  ('burek_sir',         'Burek sa sirom',      'Cheese Burek',        'food', '🥟', 3.00, '10 min', 260),
  ('sarma',             'Sarma (2 kom)',       'Sarma',               'food', '🥬', 5.00, '20 min', 270),
  ('punjene_paprike',   'Punjene paprike',     'Stuffed Peppers',     'food', '🫑', 5.00, '20 min', 280),
  ('musaka',            'Musaka',              'Moussaka',            'food', '🥘', 5.50, '20 min', 290),
  ('crni_rizoto',       'Crni rižoto',         'Black Risotto',       'food', '🦑', 8.00, '20 min', 300),
  ('pizza_margarita',   'Pica Margarita',      'Pizza Margherita',    'food', '🍕', 5.00, '15 min', 310),
  ('pizza_capricciosa', 'Pica Capricciosa',    'Pizza Capricciosa',   'food', '🍕', 6.50, '15 min', 320),
  ('pizza_quattro',     'Pica Quattro Formaggi','Pizza Four Cheese',  'food', '🍕', 7.00, '15 min', 330),
  ('pizza_pepperoni',   'Pica Pepperoni',      'Pizza Pepperoni',     'food', '🍕', 6.50, '15 min', 340),
  ('pasta_bolognese',   'Pasta Bolognese',     'Pasta Bolognese',     'food', '🍝', 6.00, '15 min', 350),
  ('pasta_carbonara',   'Pasta Carbonara',     'Pasta Carbonara',     'food', '🍝', 6.50, '15 min', 360),
  ('pasta_napolitana',  'Pasta Napolitana',    'Pasta Napolitana',    'food', '🍝', 5.50, '12 min', 370),
  ('pasta_pesto',       'Pasta Pesto',         'Pasta Pesto',         'food', '🍝', 6.00, '12 min', 380),
  ('burger_klasik',     'Burger',              'Burger',              'food', '🍔', 6.50, '12 min', 390),
  ('cheeseburger',      'Cheeseburger',        'Cheeseburger',        'food', '🍔', 7.00, '12 min', 400),
  ('piletina_burger',   'Pileći burger',       'Chicken Burger',      'food', '🍔', 6.50, '12 min', 410),
  -- Salate, predjela, prilozi
  ('cezar_salata',      'Cezar salata',        'Caesar Salad',        'salad', '🥗', 5.50, '8 min', 510),
  ('grcka_salata',      'Grčka salata',        'Greek Salad',         'salad', '🥗', 4.50, '8 min', 520),
  ('sopska_salata',     'Šopska salata',       'Shopska Salad',       'salad', '🥗', 4.00, '8 min', 530),
  ('caprese',           'Caprese',             'Caprese',             'salad', '🍅', 5.00, '8 min', 540),
  ('bruschette',        'Bruschette',          'Bruschetta',          'salad', '🥖', 4.00, '8 min', 550),
  ('pomfrit',           'Pomfrit',             'French Fries',        'salad', '🍟', 2.50, '8 min', 560),
  ('mozzarella_sticks', 'Mozzarella sticks',   'Mozzarella Sticks',   'salad', '🧀', 4.50, '10 min', 570),
  ('sezonska_salata',   'Sezonska salata',     'Seasonal Salad',      'salad', '🥗', 3.50, '6 min', 580),
  -- Doručak
  ('omlet',             'Omlet',               'Omelette',            'breakfast', '🍳', 3.50, '10 min', 610),
  ('kajgana',           'Kajgana',             'Scrambled Eggs',      'breakfast', '🍳', 3.00, '8 min', 620),
  ('palacinke_slatke',  'Palačinke (džem)',    'Pancakes (jam)',      'breakfast', '🥞', 3.50, '10 min', 630),
  ('americke_palacinke','Američke palačinke',  'American Pancakes',   'breakfast', '🥞', 4.00, '12 min', 640),
  -- Deserti
  ('baklava',           'Baklava',             'Baklava',             'dessert', '🍯', 3.00, '5 min', 710),
  ('cheesecake',        'Cheesecake',          'Cheesecake',          'dessert', '🍰', 3.50, '5 min', 720),
  ('cokoladni_kolac',   'Čokoladni kolač',     'Chocolate Cake',      'dessert', '🍫', 3.50, '5 min', 730),
  ('sladoled_kup',      'Sladoled kup',        'Ice Cream Cup',       'dessert', '🍨', 3.00, '4 min', 740),
  ('palacinke_nutela',  'Palačinke Nutela',    'Nutella Pancakes',    'dessert', '🥞', 4.00, '10 min', 750),
  ('vocna_salata',      'Voćna salata',        'Fruit Salad',         'dessert', '🍓', 3.50, '6 min', 760)
ON CONFLICT (id) DO NOTHING;

-- Pivo / vino / žestoko — stavke bez recepta (kalorije/alergeni inline).
INSERT INTO public.recipe_library (id, name, name_en, category, emoji, suggested_price, prep_time, calories, allergens, sort_order) VALUES
  ('toceno_pivo',    'Točeno pivo 0.5l', 'Draft Beer 0.5l',  'beverage', '🍺', 2.50, '1 min', 210, 'Gluten',  1010),
  ('flasirano_pivo', 'Flaširano pivo',   'Bottled Beer',     'beverage', '🍺', 2.50, '1 min', 150, 'Gluten',  1020),
  ('bijelo_vino',    'Bijelo vino (čaša)','White Wine (glass)','beverage','🥂', 2.50, '1 min', 120, 'Sulfiti', 1030),
  ('crno_vino',      'Crno vino (čaša)', 'Red Wine (glass)', 'beverage', '🍷', 2.50, '1 min', 125, 'Sulfiti', 1040),
  ('rakija_loza',    'Lozova rakija',    'Grape Brandy',     'beverage', '🥃', 2.00, '1 min', 65,  NULL,      1050),
  ('rakija_kruska',  'Kruškova rakija',  'Pear Brandy',      'beverage', '🥃', 2.50, '1 min', 65,  NULL,      1060),
  ('viski_casa',     'Viski (čaša)',     'Whisky (glass)',   'beverage', '🥃', 4.00, '1 min', 105, NULL,      1070),
  ('vinjak',         'Vinjak',           'Brandy',           'beverage', '🥃', 2.50, '1 min', 75,  NULL,      1080)
ON CONFLICT (id) DO NOTHING;

-- ─── SASTOJCI ─────────────────────────────────────────────────────────────────
INSERT INTO public.recipe_library_ingredients (recipe_id, ingredient_name, quantity, unit, sort_order) VALUES
  ('domaca_limunada',   'Sok od limuna', 60, 'ml', 1),
  ('domaca_limunada',   'Voda',          150,'ml', 2),
  ('domaca_limunada',   'Šećer',         20, 'g',  3),
  ('limunada_menta',    'Sok od limuna', 60, 'ml', 1),
  ('limunada_menta',    'Voda',          150,'ml', 2),
  ('limunada_menta',    'Šećer',         20, 'g',  3),
  ('limunada_menta',    'Menta (listići)',6, 'kom',4),
  ('ledeni_caj_breskva','Čaj (kesica)',  1,  'kom',1),
  ('ledeni_caj_breskva','Voda',          200,'ml', 2),
  ('ledeni_caj_breskva','Sirup od breskve',30,'ml',3),
  ('ledeni_caj_breskva','Led',           80, 'g',  4),
  ('ledeni_caj_limun',  'Čaj (kesica)',  1,  'kom',1),
  ('ledeni_caj_limun',  'Voda',          200,'ml', 2),
  ('ledeni_caj_limun',  'Sok od limuna', 20, 'ml', 3),
  ('ledeni_caj_limun',  'Šećer',         15, 'g',  4),
  ('ledeni_caj_limun',  'Led',           80, 'g',  5),
  ('cijedjena_pomorandza','Sok od pomorandže',250,'ml',1),
  ('frape_vanila',      'Sladoled (vanila)',1,'kom',1),
  ('frape_vanila',      'Mlijeko',       150,'ml', 2),
  ('frape_vanila',      'Led',           50, 'g',  3),
  ('frape_cokolada',    'Sladoled (vanila)',1,'kom',1),
  ('frape_cokolada',    'Mlijeko',       150,'ml', 2),
  ('frape_cokolada',    'Čokoladni sirup',20,'ml',3),
  ('frape_cokolada',    'Led',           50, 'g',  4),
  ('milkshake_jagoda',  'Sladoled (vanila)',1,'kom',1),
  ('milkshake_jagoda',  'Mlijeko',       150,'ml', 2),
  ('milkshake_jagoda',  'Jagode',        60, 'g',  3),
  ('smoothie_sumsko',   'Šumsko voće',   120,'g',  1),
  ('smoothie_sumsko',   'Banana',        1,  'kom',2),
  ('smoothie_sumsko',   'Mlijeko',       100,'ml', 3),
  ('topla_cokolada',    'Mlijeko',       200,'ml', 1),
  ('topla_cokolada',    'Čokolada',      40, 'g',  2),
  ('topla_cokolada',    'Šećer',         10, 'g',  3),
  ('caj_nana',          'Čaj od nane (kesica)',1,'kom',1),
  ('caj_nana',          'Voda',          200,'ml', 2),
  ('crni_caj',          'Čaj (kesica)',  1,  'kom',1),
  ('crni_caj',          'Voda',          200,'ml', 2),
  ('kakao',             'Mlijeko',       200,'ml', 1),
  ('kakao',             'Kakao prah',    15, 'g',  2),
  ('kakao',             'Šećer',         10, 'g',  3),
  ('cevapi',            'Mljeveno meso', 250,'g',  1),
  ('cevapi',            'Crveni luk',    30, 'g',  2),
  ('cevapi',            'Lepinja',       1,  'kom',3),
  ('pljeskavica',       'Mljeveno meso', 200,'g',  1),
  ('pljeskavica',       'Crveni luk',    20, 'g',  2),
  ('pljeskavica',       'Lepinja',       1,  'kom',3),
  ('raznjici',          'Svinjetina',    250,'g',  1),
  ('raznjici',          'Crveni luk',    20, 'g',  2),
  ('mjesano_meso',      'Svinjetina',    150,'g',  1),
  ('mjesano_meso',      'Piletina',      100,'g',  2),
  ('mjesano_meso',      'Mljeveno meso', 100,'g',  3),
  ('burek_meso',        'Kora za pitu',  150,'g',  1),
  ('burek_meso',        'Mljeveno meso', 120,'g',  2),
  ('burek_meso',        'Crveni luk',    20, 'g',  3),
  ('burek_meso',        'Ulje',          20, 'ml', 4),
  ('burek_sir',         'Kora za pitu',  150,'g',  1),
  ('burek_sir',         'Sir',           120,'g',  2),
  ('burek_sir',         'Jaje',          1,  'kom',3),
  ('burek_sir',         'Ulje',          20, 'ml', 4),
  ('sarma',             'Kupus',         150,'g',  1),
  ('sarma',             'Mljeveno meso', 150,'g',  2),
  ('sarma',             'Pirinač',       40, 'g',  3),
  ('sarma',             'Crveni luk',    20, 'g',  4),
  ('punjene_paprike',   'Paprika',       150,'g',  1),
  ('punjene_paprike',   'Mljeveno meso', 150,'g',  2),
  ('punjene_paprike',   'Pirinač',       40, 'g',  3),
  ('musaka',            'Krompir',       200,'g',  1),
  ('musaka',            'Mljeveno meso', 150,'g',  2),
  ('musaka',            'Jaje',          1,  'kom',3),
  ('musaka',            'Mlijeko',       50, 'ml', 4),
  ('crni_rizoto',       'Pirinač',       80, 'g',  1),
  ('crni_rizoto',       'Lignje',        150,'g',  2),
  ('crni_rizoto',       'Maslinovo ulje',15, 'ml', 3),
  ('crni_rizoto',       'Bijeli luk',    5,  'g',  4),
  ('pizza_margarita',   'Brašno',        200,'g',  1),
  ('pizza_margarita',   'Pasata (paradajz)',80,'g',2),
  ('pizza_margarita',   'Mocarela',      100,'g',  3),
  ('pizza_margarita',   'Maslinovo ulje',10, 'ml', 4),
  ('pizza_capricciosa', 'Brašno',        200,'g',  1),
  ('pizza_capricciosa', 'Pasata (paradajz)',80,'g',2),
  ('pizza_capricciosa', 'Mocarela',      100,'g',  3),
  ('pizza_capricciosa', 'Pršuta',        40, 'g',  4),
  ('pizza_capricciosa', 'Pečurke',       40, 'g',  5),
  ('pizza_capricciosa', 'Maslina',       20, 'g',  6),
  ('pizza_quattro',     'Brašno',        200,'g',  1),
  ('pizza_quattro',     'Pasata (paradajz)',60,'g',2),
  ('pizza_quattro',     'Mocarela',      60, 'g',  3),
  ('pizza_quattro',     'Kačkavalj',     40, 'g',  4),
  ('pizza_quattro',     'Parmezan',      30, 'g',  5),
  ('pizza_quattro',     'Sir',           40, 'g',  6),
  ('pizza_pepperoni',   'Brašno',        200,'g',  1),
  ('pizza_pepperoni',   'Pasata (paradajz)',80,'g',2),
  ('pizza_pepperoni',   'Mocarela',      100,'g',  3),
  ('pizza_pepperoni',   'Salama',        50, 'g',  4),
  ('pasta_bolognese',   'Špageti',       120,'g',  1),
  ('pasta_bolognese',   'Mljeveno meso', 100,'g',  2),
  ('pasta_bolognese',   'Pasata (paradajz)',100,'g',3),
  ('pasta_bolognese',   'Crveni luk',    20, 'g',  4),
  ('pasta_carbonara',   'Špageti',       120,'g',  1),
  ('pasta_carbonara',   'Slanina',       60, 'g',  2),
  ('pasta_carbonara',   'Jaje',          1,  'kom',3),
  ('pasta_carbonara',   'Parmezan',      30, 'g',  4),
  ('pasta_napolitana',  'Špageti',       120,'g',  1),
  ('pasta_napolitana',  'Pasata (paradajz)',120,'g',2),
  ('pasta_napolitana',  'Bosiljak',      5,  'g',  3),
  ('pasta_napolitana',  'Maslinovo ulje',10, 'ml', 4),
  ('pasta_pesto',       'Špageti',       120,'g',  1),
  ('pasta_pesto',       'Bosiljak',      20, 'g',  2),
  ('pasta_pesto',       'Parmezan',      30, 'g',  3),
  ('pasta_pesto',       'Maslinovo ulje',20, 'ml', 4),
  ('pasta_pesto',       'Orasi',         20, 'g',  5),
  ('burger_klasik',     'Pecivo (burger)',1,'kom', 1),
  ('burger_klasik',     'Mljeveno meso', 150,'g',  2),
  ('burger_klasik',     'Zelena salata', 20, 'g',  3),
  ('burger_klasik',     'Paradajz',      30, 'g',  4),
  ('burger_klasik',     'Crveni luk',    20, 'g',  5),
  ('cheeseburger',      'Pecivo (burger)',1,'kom', 1),
  ('cheeseburger',      'Mljeveno meso', 150,'g',  2),
  ('cheeseburger',      'Kačkavalj',     30, 'g',  3),
  ('cheeseburger',      'Paradajz',      30, 'g',  4),
  ('cheeseburger',      'Crveni luk',    20, 'g',  5),
  ('piletina_burger',   'Pecivo (burger)',1,'kom', 1),
  ('piletina_burger',   'Piletina',      150,'g',  2),
  ('piletina_burger',   'Zelena salata', 20, 'g',  3),
  ('piletina_burger',   'Majonez',       20, 'ml', 4),
  ('cezar_salata',      'Zelena salata', 120,'g',  1),
  ('cezar_salata',      'Piletina',      80, 'g',  2),
  ('cezar_salata',      'Parmezan',      20, 'g',  3),
  ('cezar_salata',      'Hljeb',         30, 'g',  4),
  ('cezar_salata',      'Majonez',       20, 'ml', 5),
  ('grcka_salata',      'Paradajz',      100,'g',  1),
  ('grcka_salata',      'Krastavac',     80, 'g',  2),
  ('grcka_salata',      'Feta sir',      60, 'g',  3),
  ('grcka_salata',      'Maslina',       30, 'g',  4),
  ('grcka_salata',      'Maslinovo ulje',15, 'ml', 5),
  ('grcka_salata',      'Crveni luk',    20, 'g',  6),
  ('sopska_salata',     'Paradajz',      120,'g',  1),
  ('sopska_salata',     'Krastavac',     100,'g',  2),
  ('sopska_salata',     'Sir',           50, 'g',  3),
  ('sopska_salata',     'Crveni luk',    20, 'g',  4),
  ('caprese',           'Paradajz',      120,'g',  1),
  ('caprese',           'Mocarela',      100,'g',  2),
  ('caprese',           'Bosiljak',      10, 'g',  3),
  ('caprese',           'Maslinovo ulje',15, 'ml', 4),
  ('bruschette',        'Hljeb',         80, 'g',  1),
  ('bruschette',        'Paradajz',      100,'g',  2),
  ('bruschette',        'Bijeli luk',    5,  'g',  3),
  ('bruschette',        'Maslinovo ulje',15, 'ml', 4),
  ('bruschette',        'Bosiljak',      5,  'g',  5),
  ('pomfrit',           'Pomfrit (smrznuti)',200,'g',1),
  ('pomfrit',           'Ulje',          30, 'ml', 2),
  ('pomfrit',           'So',            2,  'g',  3),
  ('mozzarella_sticks', 'Mocarela',      120,'g',  1),
  ('mozzarella_sticks', 'Brašno',        30, 'g',  2),
  ('mozzarella_sticks', 'Jaje',          1,  'kom',3),
  ('mozzarella_sticks', 'Ulje',          40, 'ml', 4),
  ('sezonska_salata',   'Zelena salata', 100,'g',  1),
  ('sezonska_salata',   'Paradajz',      80, 'g',  2),
  ('sezonska_salata',   'Krastavac',     80, 'g',  3),
  ('sezonska_salata',   'Maslinovo ulje',10, 'ml', 4),
  ('omlet',             'Jaje',          3,  'kom',1),
  ('omlet',             'Mlijeko',       20, 'ml', 2),
  ('omlet',             'Sir',           30, 'g',  3),
  ('omlet',             'Puter',         10, 'g',  4),
  ('kajgana',           'Jaje',          3,  'kom',1),
  ('kajgana',           'Puter',         10, 'g',  2),
  ('palacinke_slatke',  'Brašno',        100,'g',  1),
  ('palacinke_slatke',  'Jaje',          1,  'kom',2),
  ('palacinke_slatke',  'Mlijeko',       200,'ml', 3),
  ('palacinke_slatke',  'Šećer',         15, 'g',  4),
  ('palacinke_slatke',  'Džem',          40, 'g',  5),
  ('americke_palacinke','Brašno',        120,'g',  1),
  ('americke_palacinke','Jaje',          1,  'kom',2),
  ('americke_palacinke','Mlijeko',       150,'ml', 3),
  ('americke_palacinke','Šećer',         20, 'g',  4),
  ('americke_palacinke','Med',           30, 'g',  5),
  ('baklava',           'Kora za pitu',  80, 'g',  1),
  ('baklava',           'Orasi',         60, 'g',  2),
  ('baklava',           'Šećer',         50, 'g',  3),
  ('baklava',           'Puter',         30, 'g',  4),
  ('cheesecake',        'Krem sir',      120,'g',  1),
  ('cheesecake',        'Keks',          60, 'g',  2),
  ('cheesecake',        'Puter',         30, 'g',  3),
  ('cheesecake',        'Šećer',         30, 'g',  4),
  ('cokoladni_kolac',   'Brašno',        80, 'g',  1),
  ('cokoladni_kolac',   'Jaje',          2,  'kom',2),
  ('cokoladni_kolac',   'Čokolada',      60, 'g',  3),
  ('cokoladni_kolac',   'Šećer',         50, 'g',  4),
  ('cokoladni_kolac',   'Puter',         40, 'g',  5),
  ('sladoled_kup',      'Sladoled (vanila)',3,'kom',1),
  ('sladoled_kup',      'Šlag',          30, 'ml', 2),
  ('sladoled_kup',      'Čokoladni sirup',20,'ml', 3),
  ('palacinke_nutela',  'Brašno',        100,'g',  1),
  ('palacinke_nutela',  'Jaje',          1,  'kom',2),
  ('palacinke_nutela',  'Mlijeko',       200,'ml', 3),
  ('palacinke_nutela',  'Nutela',        50, 'g',  4),
  ('vocna_salata',      'Voće (sezonsko)',200,'g', 1),
  ('vocna_salata',      'Med',           20, 'g',  2)
ON CONFLICT DO NOTHING;

-- ─── IZRAČUN KALORIJA + ALERGENA (samo za nove kategorije) ─────────────────────
CREATE TEMP TABLE ing_map2 (nm TEXT PRIMARY KEY, kcal NUMERIC, allergens TEXT[]) ON COMMIT DROP;
INSERT INTO ing_map2 (nm, kcal, allergens) VALUES
  -- reused (iz pića)
  ('sok od limuna',0.22,'{}'), ('voda',0,'{}'), ('šećer',4.0,'{}'),
  ('menta (listići)',0,'{}'), ('led',0,'{}'), ('sok od pomorandže',0.45,'{}'),
  ('sladoled (vanila)',140,ARRAY['Mlijeko','Jaja']), ('mlijeko',0.64,ARRAY['Mlijeko']),
  ('čokoladni sirup',3.0,'{}'), ('šlag',2.9,ARRAY['Mlijeko']),
  -- pića (novo)
  ('čaj (kesica)',0,'{}'), ('čaj od nane (kesica)',0,'{}'),
  ('sirup od breskve',2.6,'{}'), ('jagode',0.32,'{}'), ('šumsko voće',0.45,'{}'),
  ('banana',90,'{}'), ('čokolada',5.5,ARRAY['Mlijeko']), ('kakao prah',3.7,'{}'),
  -- meso/riba
  ('mljeveno meso',2.5,'{}'), ('svinjetina',2.6,'{}'), ('piletina',1.65,'{}'),
  ('slanina',5.4,'{}'), ('pršuta',2.5,'{}'), ('salama',4.5,'{}'),
  ('lignje',0.92,ARRAY['Mekušci']), ('jaje',70,ARRAY['Jaja']),
  -- mliječno
  ('sir',3.5,ARRAY['Mlijeko']), ('kačkavalj',3.6,ARRAY['Mlijeko']),
  ('mocarela',2.8,ARRAY['Mlijeko']), ('parmezan',4.0,ARRAY['Mlijeko']),
  ('feta sir',2.6,ARRAY['Mlijeko']), ('puter',7.2,ARRAY['Mlijeko']),
  ('krem sir',3.4,ARRAY['Mlijeko']),
  -- žitarice/skrob
  ('brašno',3.6,ARRAY['Gluten']), ('špageti',3.7,ARRAY['Gluten']),
  ('pirinač',3.6,'{}'), ('hljeb',2.6,ARRAY['Gluten']), ('lepinja',200,ARRAY['Gluten']),
  ('pecivo (burger)',250,ARRAY['Gluten']), ('kora za pitu',3.4,ARRAY['Gluten']),
  ('keks',4.8,ARRAY['Gluten','Mlijeko']), ('krompir',0.77,'{}'),
  ('pomfrit (smrznuti)',1.5,'{}'),
  -- povrće
  ('paradajz',0.18,'{}'), ('pasata (paradajz)',0.30,'{}'), ('krastavac',0.15,'{}'),
  ('crveni luk',0.40,'{}'), ('bijeli luk',1.49,'{}'), ('paprika',0.27,'{}'),
  ('zelena salata',0.15,'{}'), ('maslina',1.15,'{}'), ('pečurke',0.22,'{}'),
  ('kupus',0.25,'{}'), ('bosiljak',0.23,'{}'),
  -- masti/dodaci
  ('maslinovo ulje',8.84,'{}'), ('ulje',8.84,'{}'), ('majonez',6.80,ARRAY['Jaja']),
  ('so',0,'{}'),
  -- slatko
  ('nutela',5.39,ARRAY['Mlijeko','Orašasti plodovi']), ('orasi',6.54,ARRAY['Orašasti plodovi']),
  ('med',3.04,'{}'), ('džem',2.5,'{}'), ('voće (sezonsko)',0.50,'{}');

-- Kalorije (samo nove kategorije s receptom)
UPDATE public.recipe_library r SET calories = sub.kcal
FROM (
  SELECT ri.recipe_id, round(sum(ri.quantity * COALESCE(m.kcal,0)))::int AS kcal
  FROM public.recipe_library_ingredients ri
  JOIN public.recipe_library rl ON rl.id = ri.recipe_id
  LEFT JOIN ing_map2 m ON lower(ri.ingredient_name) = m.nm
  WHERE rl.category IN ('soft','hot','food','salad','breakfast','dessert')
  GROUP BY ri.recipe_id
) sub
WHERE sub.recipe_id = r.id;

-- Alergeni (samo nove kategorije s receptom)
UPDATE public.recipe_library r SET allergens = sub.al
FROM (
  SELECT ri.recipe_id, string_agg(DISTINCT a, ', ' ORDER BY a) AS al
  FROM public.recipe_library_ingredients ri
  JOIN public.recipe_library rl ON rl.id = ri.recipe_id
  JOIN ing_map2 m ON lower(ri.ingredient_name) = m.nm
  CROSS JOIN LATERAL unnest(m.allergens) AS a
  WHERE rl.category IN ('soft','hot','food','salad','breakfast','dessert')
  GROUP BY ri.recipe_id
) sub
WHERE sub.recipe_id = r.id;
