-- Seed biblioteke: KAFA i KOKTELI (faza 1)
-- Recepti (lista sastojaka + količine) su činjenice — autorski neutralno.
-- Količine su standardne (espresso baza 7g; koktel mjere u ml). Tenant doradi po želji.
-- Idempotentno: ON CONFLICT DO NOTHING (migracija je nepromjenjiva, ali ovo štiti re-run u testu).

-- ─── KAFA ─────────────────────────────────────────────────────────────────────
INSERT INTO public.recipe_library (id, name, name_en, category, emoji, suggested_price, sort_order) VALUES
  ('espresso',         'Espreso',            'Espresso',          'coffee', '☕', 1.20, 10),
  ('doppio',           'Doppio',             'Doppio',            'coffee', '☕', 1.80, 20),
  ('ristretto',        'Ristreto',           'Ristretto',         'coffee', '☕', 1.30, 30),
  ('lungo',            'Lungo',              'Lungo',             'coffee', '☕', 1.40, 40),
  ('macchiato',        'Makjato',            'Macchiato',         'coffee', '☕', 1.50, 50),
  ('cortado',          'Kortado',            'Cortado',           'coffee', '☕', 1.80, 60),
  ('cappuccino',       'Kapučino',           'Cappuccino',        'coffee', '☕', 1.80, 70),
  ('flat_white',       'Flat White',         'Flat White',        'coffee', '☕', 2.20, 80),
  ('caffe_latte',      'Kafa latte',         'Caffè Latte',       'coffee', '☕', 2.20, 90),
  ('latte_macchiato',  'Latte makjato',      'Latte Macchiato',   'coffee', '☕', 2.30, 100),
  ('americano',        'Americano',          'Americano',         'coffee', '☕', 1.50, 110),
  ('mocha',            'Moka',               'Mocha',             'coffee', '☕', 2.50, 120),
  ('caramel_macchiato','Karamel makjato',    'Caramel Macchiato', 'coffee', '☕', 2.60, 130),
  ('affogato',         'Afogato',            'Affogato',          'coffee', '🍨', 2.80, 140),
  ('irish_coffee',     'Irska kafa',         'Irish Coffee',      'coffee', '☕', 4.50, 150),
  ('vienna_coffee',    'Bečka kafa',         'Vienna Coffee',     'coffee', '☕', 2.80, 160),
  ('cold_brew',        'Cold brew',          'Cold Brew',         'coffee', '🧊', 2.80, 170),
  ('iced_latte',       'Ledena latte',       'Iced Latte',        'coffee', '🧊', 2.60, 180)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipe_library_ingredients (recipe_id, ingredient_name, quantity, unit, sort_order) VALUES
  ('espresso',         'Kafa (espreso)', 7,   'g',  1),
  ('doppio',           'Kafa (espreso)', 14,  'g',  1),
  ('ristretto',        'Kafa (espreso)', 7,   'g',  1),
  ('lungo',            'Kafa (espreso)', 7,   'g',  1),
  ('lungo',            'Voda',           30,  'ml', 2),
  ('macchiato',        'Kafa (espreso)', 7,   'g',  1),
  ('macchiato',        'Mlijeko',        30,  'ml', 2),
  ('cortado',          'Kafa (espreso)', 7,   'g',  1),
  ('cortado',          'Mlijeko',        60,  'ml', 2),
  ('cappuccino',       'Kafa (espreso)', 7,   'g',  1),
  ('cappuccino',       'Mlijeko',        120, 'ml', 2),
  ('flat_white',       'Kafa (espreso)', 14,  'g',  1),
  ('flat_white',       'Mlijeko',        120, 'ml', 2),
  ('caffe_latte',      'Kafa (espreso)', 7,   'g',  1),
  ('caffe_latte',      'Mlijeko',        200, 'ml', 2),
  ('latte_macchiato',  'Kafa (espreso)', 7,   'g',  1),
  ('latte_macchiato',  'Mlijeko',        220, 'ml', 2),
  ('americano',        'Kafa (espreso)', 7,   'g',  1),
  ('americano',        'Voda',           90,  'ml', 2),
  ('mocha',            'Kafa (espreso)', 7,   'g',  1),
  ('mocha',            'Mlijeko',        150, 'ml', 2),
  ('mocha',            'Čokoladni sirup',20,  'ml', 3),
  ('caramel_macchiato','Kafa (espreso)', 7,   'g',  1),
  ('caramel_macchiato','Mlijeko',        200, 'ml', 2),
  ('caramel_macchiato','Karamel sirup',  20,  'ml', 3),
  ('affogato',         'Kafa (espreso)', 7,   'g',  1),
  ('affogato',         'Sladoled (vanila)', 1,'kom',2),
  ('irish_coffee',     'Kafa (espreso)', 7,   'g',  1),
  ('irish_coffee',     'Viski',          40,  'ml', 2),
  ('irish_coffee',     'Šlag',           20,  'ml', 3),
  ('irish_coffee',     'Šećer',          10,  'g',  4),
  ('vienna_coffee',    'Kafa (espreso)', 14,  'g',  1),
  ('vienna_coffee',    'Šlag',           30,  'ml', 2),
  ('cold_brew',        'Kafa (espreso)', 20,  'g',  1),
  ('cold_brew',        'Voda',           200, 'ml', 2),
  ('iced_latte',       'Kafa (espreso)', 14,  'g',  1),
  ('iced_latte',       'Mlijeko',        150, 'ml', 2),
  ('iced_latte',       'Led',            100, 'g',  3)
ON CONFLICT DO NOTHING;

-- ─── KOKTELI ──────────────────────────────────────────────────────────────────
INSERT INTO public.recipe_library (id, name, name_en, category, emoji, suggested_price, sort_order) VALUES
  ('mojito',           'Mojito',             'Mojito',             'cocktail', '🍹', 7.00, 10),
  ('margarita',        'Margarita',          'Margarita',          'cocktail', '🍸', 7.50, 20),
  ('daiquiri',         'Dajkiri',            'Daiquiri',           'cocktail', '🍸', 7.00, 30),
  ('negroni',          'Negroni',            'Negroni',            'cocktail', '🍸', 8.00, 40),
  ('old_fashioned',    'Old Fashioned',      'Old Fashioned',      'cocktail', '🥃', 8.50, 50),
  ('manhattan',        'Manhattan',          'Manhattan',          'cocktail', '🥃', 8.50, 60),
  ('cosmopolitan',     'Kosmopolitan',       'Cosmopolitan',       'cocktail', '🍸', 7.50, 70),
  ('mai_tai',          'Mai Tai',            'Mai Tai',            'cocktail', '🍹', 8.00, 80),
  ('pina_colada',      'Piña Colada',        'Piña Colada',        'cocktail', '🍹', 7.50, 90),
  ('caipirinha',       'Kajpirinja',         'Caipirinha',         'cocktail', '🍹', 7.00, 100),
  ('whiskey_sour',     'Whiskey Sour',       'Whiskey Sour',       'cocktail', '🥃', 7.50, 110),
  ('aperol_spritz',    'Aperol Spritz',      'Aperol Spritz',      'cocktail', '🥂', 6.50, 120),
  ('tom_collins',      'Tom Collins',        'Tom Collins',        'cocktail', '🍸', 7.00, 130),
  ('gin_tonic',        'Džin tonik',         'Gin & Tonic',        'cocktail', '🍸', 6.00, 140),
  ('cuba_libre',       'Cuba Libre',         'Cuba Libre',         'cocktail', '🍹', 6.00, 150),
  ('bloody_mary',      'Bloody Mary',        'Bloody Mary',        'cocktail', '🍅', 7.00, 160),
  ('long_island',      'Long Island Iced Tea','Long Island Iced Tea','cocktail','🍸', 8.50, 170),
  ('espresso_martini', 'Espresso Martini',   'Espresso Martini',   'cocktail', '🍸', 8.00, 180),
  ('moscow_mule',      'Moscow Mule',        'Moscow Mule',        'cocktail', '🍹', 7.00, 190),
  ('mimosa',           'Mimoza',             'Mimosa',             'cocktail', '🥂', 6.00, 200),
  ('bellini',          'Belini',             'Bellini',            'cocktail', '🥂', 6.50, 210),
  ('sex_on_the_beach', 'Sex on the Beach',   'Sex on the Beach',   'cocktail', '🍹', 7.50, 220),
  ('tequila_sunrise',  'Tequila Sunrise',    'Tequila Sunrise',    'cocktail', '🍹', 7.00, 230),
  ('dark_n_stormy',    'Dark ''n'' Stormy',  'Dark ''n'' Stormy',  'cocktail', '🍹', 7.50, 240),
  ('gimlet',           'Gimlet',             'Gimlet',             'cocktail', '🍸', 7.00, 250),
  ('white_russian',    'White Russian',      'White Russian',      'cocktail', '🥃', 7.50, 260),
  ('mint_julep',       'Mint Julep',         'Mint Julep',         'cocktail', '🥃', 8.00, 270),
  ('french_75',        'French 75',          'French 75',          'cocktail', '🥂', 8.00, 280)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.recipe_library_ingredients (recipe_id, ingredient_name, quantity, unit, sort_order) VALUES
  ('mojito',           'Bijeli rum',          50,  'ml',  1),
  ('mojito',           'Limeta',              1,   'kom', 2),
  ('mojito',           'Menta (listići)',     8,   'kom', 3),
  ('mojito',           'Šećer',               10,  'g',   4),
  ('mojito',           'Soda voda',           100, 'ml',  5),
  ('margarita',        'Tekila',              50,  'ml',  1),
  ('margarita',        'Triple sec',          20,  'ml',  2),
  ('margarita',        'Sok od limete',       20,  'ml',  3),
  ('margarita',        'So',                  2,   'g',   4),
  ('daiquiri',         'Bijeli rum',          50,  'ml',  1),
  ('daiquiri',         'Sok od limete',       25,  'ml',  2),
  ('daiquiri',         'Šećerni sirup',       15,  'ml',  3),
  ('negroni',          'Džin',                30,  'ml',  1),
  ('negroni',          'Campari',             30,  'ml',  2),
  ('negroni',          'Crveni vermut',       30,  'ml',  3),
  ('old_fashioned',    'Burbon',              50,  'ml',  1),
  ('old_fashioned',    'Šećer',               5,   'g',   2),
  ('old_fashioned',    'Angostura biter',     1,   'ml',  3),
  ('manhattan',        'Ražani viski',        50,  'ml',  1),
  ('manhattan',        'Crveni vermut',       20,  'ml',  2),
  ('manhattan',        'Angostura biter',     1,   'ml',  3),
  ('cosmopolitan',     'Votka',               40,  'ml',  1),
  ('cosmopolitan',     'Triple sec',          15,  'ml',  2),
  ('cosmopolitan',     'Sok od limete',       15,  'ml',  3),
  ('cosmopolitan',     'Sok od brusnice',     30,  'ml',  4),
  ('mai_tai',          'Bijeli rum',          40,  'ml',  1),
  ('mai_tai',          'Tamni rum',           20,  'ml',  2),
  ('mai_tai',          'Triple sec',          15,  'ml',  3),
  ('mai_tai',          'Orgeat sirup',        15,  'ml',  4),
  ('mai_tai',          'Sok od limete',       20,  'ml',  5),
  ('pina_colada',      'Bijeli rum',          50,  'ml',  1),
  ('pina_colada',      'Kokosovo mlijeko',    30,  'ml',  2),
  ('pina_colada',      'Sok od ananasa',      90,  'ml',  3),
  ('caipirinha',       'Cachaça',             60,  'ml',  1),
  ('caipirinha',       'Limeta',              1,   'kom', 2),
  ('caipirinha',       'Šećer',               10,  'g',   3),
  ('whiskey_sour',     'Burbon',              50,  'ml',  1),
  ('whiskey_sour',     'Sok od limuna',       25,  'ml',  2),
  ('whiskey_sour',     'Šećerni sirup',       15,  'ml',  3),
  ('whiskey_sour',     'Bjelance',            1,   'kom', 4),
  ('aperol_spritz',    'Aperol',              60,  'ml',  1),
  ('aperol_spritz',    'Prosecco',            90,  'ml',  2),
  ('aperol_spritz',    'Soda voda',           30,  'ml',  3),
  ('tom_collins',      'Džin',                50,  'ml',  1),
  ('tom_collins',      'Sok od limuna',       25,  'ml',  2),
  ('tom_collins',      'Šećerni sirup',       15,  'ml',  3),
  ('tom_collins',      'Soda voda',           60,  'ml',  4),
  ('gin_tonic',        'Džin',                50,  'ml',  1),
  ('gin_tonic',        'Tonik',               150, 'ml',  2),
  ('cuba_libre',       'Bijeli rum',          50,  'ml',  1),
  ('cuba_libre',       'Cola',                120, 'ml',  2),
  ('cuba_libre',       'Limeta',              1,   'kom', 3),
  ('bloody_mary',      'Votka',               45,  'ml',  1),
  ('bloody_mary',      'Sok od paradajza',    90,  'ml',  2),
  ('bloody_mary',      'Sok od limuna',       15,  'ml',  3),
  ('bloody_mary',      'Vorčester sos',       2,   'ml',  4),
  ('bloody_mary',      'Tabasko',             1,   'ml',  5),
  ('long_island',      'Votka',               15,  'ml',  1),
  ('long_island',      'Džin',                15,  'ml',  2),
  ('long_island',      'Bijeli rum',          15,  'ml',  3),
  ('long_island',      'Tekila',              15,  'ml',  4),
  ('long_island',      'Triple sec',          15,  'ml',  5),
  ('long_island',      'Sok od limuna',       25,  'ml',  6),
  ('long_island',      'Cola',                30,  'ml',  7),
  ('espresso_martini', 'Votka',               50,  'ml',  1),
  ('espresso_martini', 'Liker od kafe',       20,  'ml',  2),
  ('espresso_martini', 'Kafa (espreso)',      7,   'g',   3),
  ('espresso_martini', 'Šećerni sirup',       10,  'ml',  4),
  ('moscow_mule',      'Votka',               50,  'ml',  1),
  ('moscow_mule',      'Sok od limete',       15,  'ml',  2),
  ('moscow_mule',      'Đumbirovo pivo',      120, 'ml',  3),
  ('mimosa',           'Prosecco',            75,  'ml',  1),
  ('mimosa',           'Sok od pomorandže',   75,  'ml',  2),
  ('bellini',          'Prosecco',            100, 'ml',  1),
  ('bellini',          'Pire od breskve',     50,  'ml',  2),
  ('sex_on_the_beach', 'Votka',               40,  'ml',  1),
  ('sex_on_the_beach', 'Liker od breskve',    20,  'ml',  2),
  ('sex_on_the_beach', 'Sok od pomorandže',   40,  'ml',  3),
  ('sex_on_the_beach', 'Sok od brusnice',     40,  'ml',  4),
  ('tequila_sunrise',  'Tekila',              45,  'ml',  1),
  ('tequila_sunrise',  'Sok od pomorandže',   90,  'ml',  2),
  ('tequila_sunrise',  'Grenadina',           15,  'ml',  3),
  ('dark_n_stormy',    'Tamni rum',           60,  'ml',  1),
  ('dark_n_stormy',    'Đumbirovo pivo',      100, 'ml',  2),
  ('dark_n_stormy',    'Limeta',              1,   'kom', 3),
  ('gimlet',           'Džin',                60,  'ml',  1),
  ('gimlet',           'Sok od limete',       15,  'ml',  2),
  ('gimlet',           'Šećerni sirup',       15,  'ml',  3),
  ('white_russian',    'Votka',               50,  'ml',  1),
  ('white_russian',    'Liker od kafe',       20,  'ml',  2),
  ('white_russian',    'Pavlaka',             30,  'ml',  3),
  ('mint_julep',       'Burbon',              60,  'ml',  1),
  ('mint_julep',       'Menta (listići)',     8,   'kom', 2),
  ('mint_julep',       'Šećer',               10,  'g',   3),
  ('french_75',        'Džin',                30,  'ml',  1),
  ('french_75',        'Sok od limuna',       15,  'ml',  2),
  ('french_75',        'Šećerni sirup',       10,  'ml',  3),
  ('french_75',        'Šampanjac',           60,  'ml',  4)
ON CONFLICT DO NOTHING;
